- include_tasks: install.yml

- include_tasks: php_sites.yml
- include_tasks: reverse_proxies.yml
  vars:
    nginx_reverse_proxies_plus_vouch: >
      {{
        (
          (nginx_reverse_proxies | dict2items) +
          [{'key': vouch_host_name, 'value': {'host': '127.0.0.1', 'port': vouch_port}}]
        ) | items2dict
      }}

- include_tasks: vouch.yml
  when: ((vouch_nextcloud_client_id | length) > 0) and ((vouch_nextcloud_client_secret | length) > 0)
  tags: [ vouch ]
