- include_tasks: install.yml

- include_tasks: php_sites.yml
- include_tasks: reverse_proxies.yml

- include_tasks: cnames.yml
  tags: [ pihole ]
- include_tasks: vouch.yml
  when: (((vouch_nextcloud_client_id | length) > 0) and ((vouch_nextcloud_client_secret | length) > 0)) or ((vouch_homeassistant_url | length) > 0)
  tags: [ vouch ]
