- name: Create Proxy Certificates
  include_role:
    name: generate_certificate
  with_items: "{{ nginx_php_sites | dict2items }}"
  vars:
    certificate_hostname: "{{ item.key }}"

- name: Template PHP Site Configs
  template:
    src: reverse_proxies/php_template.nginx.j2
    dest: "/etc/nginx/sites-available/{{ item.key }}.conf"
    lstrip_blocks: true
    trim_blocks: true
  notify: Reload nginx
  with_items: "{{ nginx_php_sites | dict2items }}"

- name: Enable PHP Sites
  file:
    src: "../sites-available/{{ item.key }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}.conf"
    force: true
    state: link
  notify: Reload nginx
  with_items: "{{ nginx_php_sites | dict2items }}"
