variables:
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_HOST_KEY_CHECKING: "false"

stages:
  - check
  - deploy

# Default cache settings
cache:
  - key: "Galaxy - $CI_COMMIT_REF_NAME"
    paths:
      - .ansible/roles$CI_CONCURRENT_PROJECT_ID/
      - .ansible/collections$CI_CONCURRENT_PROJECT_ID/
    policy: pull-push
  - key: "Facts - $CI_COMMIT_REF_NAME"
    paths:
      - .ansible/facts$CI_CONCURRENT_PROJECT_ID/
    policy: pull-push

before_script:
  - mkdir -p .ansible/{roles,collections,facts}$CI_CONCURRENT_PROJECT_ID ~/.ansible /tmp/ansible
  - ln -s "${PWD}/.ansible/roles$CI_CONCURRENT_PROJECT_ID/" ~/.ansible/roles
  - ln -s "${PWD}/.ansible/collections$CI_CONCURRENT_PROJECT_ID/" ~/.ansible/collections
  - ln -s "${PWD}/.ansible/facts$CI_CONCURRENT_PROJECT_ID/" /tmp/ansible/facts
  - ansible-galaxy install -r requirements.yml
  - ansible-galaxy collection install -r requirements.yml

# Tasks
check:
  resource_group: ansible
  stage: check
  script:
    - ./run.sh -C

deploy:
  resource_group: ansible
  stage: deploy
  needs:
    - check
  script:
    - ./run.sh
  only:
    refs:
      - master
