variables:
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_HOST_KEY_CHECKING: "false"

stages:
  - check
  - deploy

before_script:
  - mkdir -p ~/.ansible /tmp/ansible
  - ansible-galaxy install -r requirements.yml
  - ansible-galaxy collection install -r requirements.yml

# Tasks
check:
  resource_group: ansible
  stage: check
  script:
    - ./run.sh -C

deploy:
  resource_group: ansible
  stage: deploy
  needs:
    - check
  script:
    - ./run.sh
  only:
    refs:
      - master
