- hosts: homeserver
  roles:
    # Most important things
    - { name: brainstone.user_management, tags: [ auth, security, user_management ] }
    - { name: base, tags: base }
    
    # Normal stuff
    - { name: borg, tags: borg }
    - { name: chrony, tags: [ chrony, ntp ] }
    - { name: fail2ban, tags: [ fail2ban, security ] }
    
    # Early stuff
    - { name: nginx, tags: nginx }
    - { name: certbot, tags: [ certbot, security ] }
    - { name: docker, tags: docker }
    
    # Software stuff
    - { name: gitlab_runner, tags: gitlab_runner, when: gitlab_runner_token is defined }
    - { name: r_pufky.pihole, tags: pihole }
