- hosts: homeserver
  roles:
    # Most important things
    - { name: brainstone.user_management, tags: [ auth, security, user_management ] }
    - { name: base, tags: base }

    # Network
    - { name: bridge, tags: [ bridge, network ] }
    
    # Normal stuff
    - { name: borg, tags: borg }
    - { name: chrony, tags: [ chrony, ntp ] }
    - { name: fail2ban, tags: [ fail2ban, security ] }
    
    # Early stuff
    - { name: nginx, tags: nginx }
    - { name: certbot, tags: [ certbot, security ] }
    - { name: docker, tags: docker }
    
    # Software stuff
    - { name: heimdall, tags: [ heimdall, nginx ] }
    - { name: gitlab_runner, tags: gitlab_runner, when: gitlab_runner_token is defined }
#    - { name: r_pufky.pihole, tags: [ pihole, nginx ] }
#    - { name: brainstone.wireguard_easy, tags: [ wireguard_easy, wireguard, nginx ] }
    - { name: home_assistant, tags: [ home_assistant, nginx ] }
    - { name: telegraf, tags: telegraf }
    - { name: rsyslog_via_telegraf, tags: [ rsyslog, telegraf ] }
    - { name: fileshare, tags: [ fileshare, samba ] }
