collections:
  - ansible.utils
  - community.general
  - community.libvirt

roles:
  - src: brainstone.user_management
  - src: brainstone.wireguard_easy
  - src: r_pufky.pihole
  - src: dj-wasabi.telegraf
  - src: geerlingguy.nodejs
