---
# PHP Settings
php_versions:
  - "8.1"

php_extra_packages: [ ]

# nginx pages
nginx_base_name: "localhost"

nginx_php_sites: { }

nginx_reverse_proxies: { }

# vouch-proxy settings
vouch_base_domain: "{{ inventory_hostname }}"
vouch_host_name: "vouch.{{ vouch_base_domain }}"
vouch_port: 9100
vouch_path: '/opt/vouch-proxy'
vouch_user: 'vouch-proxy'

# Automatically detect all local networks
vouch_local_networks: >
  {{
    (
      ansible_facts | dict2items |
      selectattr('value.active', 'true') |
      selectattr('value.ipv4', 'defined') |
      json_query('[].value.ipv4.[network, netmask].join(`/`, @)') |
      map('ansible.utils.ipaddr', 'network/prefix') |
      ipaddr('int') | sort | ipaddr 
      + 
      ansible_facts | dict2items |
      selectattr('value.active', 'true') |
      selectattr('value.ipv6', 'defined') |
      json_query('[].value.ipv6[].[address, prefix][*].join(`/`, @)') |
      map('ansible.utils.ipaddr', 'network/prefix') |
      ipaddr('int') | sort | ipaddr 
    ) | unique
  }}

# vouch-proxy nextcloud peer
vouch_nextcloud_url: "https://cloud.project-creative.net"
vouch_nextcloud_client_id: ""
vouch_nextcloud_client_secret: ""

# vouch-proxy homeassistant peer
vouch_homeassistant_url: ""
