---
- name: Update Heimdall repo
  git:
    repo: "https://github.com/linuxserver/Heimdall.git"
    dest: "{{ heimdall_base_dir }}"
    clone: true
    update: true
    force: true
    depth: 1
    single_branch: true

- name: Generates key
  shell: |
    cp .env.template .env
    php{{ heimdall_php_version }} artisan key:generate
  args:
    chdir: "{{ heimdall_base_dir }}"
    creates: "{{ heimdall_base_dir }}/.env"
