---
- name: Install pv and libcdio-utils
  apt:
    pkg:
      - pv
      - libcdio-utils
    update_cache: false

- name: Copy auto_iso.sh.j2 to /usr/local/bin/auto_iso and make it executable
  template:
    src: templates/auto_iso.sh.j2
    dest: /usr/local/bin/auto_iso
    owner: root
    group: root
    mode: 0755
