---
- name: Install beep, libcdio-utils and pv
  apt:
    pkg:
      - beep
      - libcdio-utils
      - pv
    update_cache: false

- name: Copy auto_iso.sh.j2 to /usr/local/bin/auto_iso and make it executable
  template:
    src: auto_iso.sh.j2
    dest: /usr/local/bin/auto_iso
    owner: root
    group: root
    mode: 0755

- name: Template auto_iso systemd file
  template:
    src: auto_iso@.service.j2
    dest: /etc/systemd/system/auto_iso@.service
  notify: Reload systemd

- name: Add udev rule
  copy:
    dest: /etc/udev/rules.d/99-cd-dvd.rules
    content: |
      KERNEL=="sr*", ACTION=="change", ENV{ID_FS_TYPE}!="", TAG+="systemd", PROGRAM="/bin/systemd-escape -p %E{DEVNAME}", ENV{SYSTEMD_WANTS}="auto_iso@%c.service"
  notify:
    - Reload udev
