- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: remove default Jail
  file:
    dest: /etc/fail2ban/jail.d/defaults-debian.conf
    state: absent
  notify: Restart fail2ban

- name: sshd Jail
  vars:
    fail2ban_jail_name: sshd
    fail2ban_filter: sshd
    fail2ban_port: ssh
    fail2ban_logpath: sshd_log
  template:
    src: fail2ban.conf.j2
    dest: "/etc/fail2ban/jail.d/{{ fail2ban_jail_name }}.conf"
  notify: Restart fail2ban

- name: Enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: true
