---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Reload udev
  systemd:
    name: systemd-udevd.service
    state: restarted

- name: Reload samba
  systemd:
    name: smbd.service
    state: restarted
